version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: delivery_order_db
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
      POSTGRES_DB: pg
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data